### ISSUE TITLE
User can save a note.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/web-api#1]
# Motivation

We want to be able to save a note to the web api.

# Task Implementation
- [ ] Set up repo 
- [ ] Be able to link all the pages together
- [ ] Add Event Handlers for this saving
- [ ] Be able to save a note
- [ ] Be able to see the changes made. 

# Wireframe

Coming soon
