### ISSUE TITLE
User can read a list of notes.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/web-api#2]
# Motivation
Now that we can post our notes, we want to be able to view them, preferably on a page of some sort.

# Task implementation. 
- [ ] register a verb GET
- [ ] handle its request and its response
- [ ] Test it out. 

# Wireframe
Coming soon
