### ISSUE TITLE
User can update a note by id.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/web-api#3]
# Motivation
We want to be able to update a list of notes now

# Task implementation
- [ ] Create a method for updating (PUT)
- [ ] Make sure that the verb correctly registers by finding the proper note id and the matching item.
- [ ] Use GET to verify that the notes are updated correctly.
