### ISSUE TITLE
User can delete a note by id.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/web-api#4]
# Motivation
We now want to fully operate this server by adding a delete function

# Task implementation
- [x] register app.delete
- [x] Get its definition
- [x] Verify that it works in cases of existing and non-existing ID's
- [x] Test it out.
